door:
  build: door
  cap_add:
    - SYS_RAWIO
  devices:
    - /dev/mem
  environment:
    LOCK_GPIO_PIN: 11
    UNLOCK_DURATION: 10
    SECRET_KEY: abc
  ports:
    - "5000:5000"

jukebox:
  build: jukebox
  devices:
    - /dev/snd
  ports:
    - "6600:6600"
    - "6680:6680"

